taxi/urls.py
from django.urls import path

from taxi.views import (
    index, CarListView, CarDetailView, DriverListView, DriverDetailView,
    ManufacturerListView, ManufacturerCreateView, ManufacturerUpdateView,
    ManufacturerDeleteView, CarCreateView, CarUpdateView, CarDeleteView,
    DriverCreateView, DriverUpdateView, LicenseUpdateView, DriverDeleteView
)

urlpatterns = [
    path("", index, name="index"),
    path(
        "manufacturers/",
        ManufacturerListView.as_view(),
        name="manufacturer-list"
    ),
    path(
        "manufacturers/create/",
        ManufacturerCreateView.as_view(),
        name="manufacturer-create"
    ),
    path(
        "manufacturers/<int:pk>/update/",
        ManufacturerUpdateView.as_view(),
        name="manufacturer-update"
    ),
    path(
        "manufacturers/<int:pk>/delete/",
        ManufacturerDeleteView.as_view(),
        name="manufacturer-delete"
    ),
    path("cars/", CarListView.as_view(), name="car-list"),
    path("cars/<int:pk>/", CarDetailView.as_view(), name="car-detail"),
    path("cars/create/", CarCreateView.as_view(), name="car-create"),
    path("cars/<int:pk>/update/", CarUpdateView.as_view(), name="car-update"),
    path("cars/<int:pk>/delete/", CarDeleteView.as_view(), name="car-delete"),
    path("drivers/", DriverListView.as_view(), name="driver-list"),
    path(
        "drivers/<int:pk>/",
        DriverDetailView.as_view(),
        name="driver-detail"
    ),
    path(
        "drivers/create/",
        DriverCreateView.as_view(),
        name="driver-create"
    ),
    path(
        "drivers/<int:pk>/update/",
        DriverUpdateView.as_view(),
        name="driver-update"
    ),
    path(
        "drivers/<int:pk>/license-update/",
        LicenseUpdateView.as_view(),
        name="license-update"
    ),
    path(
        "drivers/<int:pk>/delete/",
        DriverDeleteView.as_view(),
        name="driver-delete"
    ),
]

app_name = "taxi"

taxi_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("taxi.urls", namespace="taxi")),
    path("accounts/", include("django.contrib.auth.urls")),
    path('__debug__/', include('debug_toolbar.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

taxi/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.urls import reverse


class Manufacturer(models.Model):
    name = models.CharField(max_length=255)
    country = models.CharField(max_length=255)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name} ({self.country})"


class Driver(AbstractUser):
    license_number = models.CharField(max_length=255, unique=True)

    class Meta:
        verbose_name = "driver"
        verbose_name_plural = "drivers"
        ordering = ["username"]

    def get_absolute_url(self):
        return reverse("taxi:driver-detail", kwargs={'pk': self.pk})

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"


class Car(models.Model):
    model = models.CharField(max_length=255)
    manufacturer = models.ForeignKey(Manufacturer, on_delete=models.CASCADE)
    drivers = models.ManyToManyField(Driver, related_name="cars")

    class Meta:
        ordering = ["model"]

    def __str__(self):
        return f"{self.model} ({self.manufacturer.name})"

taxi/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.contrib.auth import get_user_model
from django import forms

from taxi.models import Driver, Car


class DriverCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = Driver
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "license_number",
        )


class LicenseForm(forms.ModelForm):
    LICENSE_NUMBER_LENGTH = 8
    LICENSE_NUMBER_UPPERCASE = 3
    LICENSE_NUMBER_DIGITS = 5

    class Meta:
        model = Driver
        fields = ("license_number",)

    def clean_license_number(self):
        license_number = self.cleaned_data["license_number"]

        if len(license_number) != LicenseForm.LICENSE_NUMBER_LENGTH:
            raise ValidationError(
                "License Number must contain only "
                f"{LicenseForm.LICENSE_NUMBER_LENGTH} characters"
            )

        if not license_number[:LicenseForm.LICENSE_NUMBER_UPPERCASE].isupper():
            raise ValidationError(
                f"First {LicenseForm.LICENSE_NUMBER_UPPERCASE} "
                "characters must be uppercase"
            )

        if not license_number[-LicenseForm.LICENSE_NUMBER_DIGITS:].isdigit():
            raise ValidationError(
                f"Last {LicenseForm.LICENSE_NUMBER_DIGITS} "
                "characters must be digits"
            )

        return license_number


class CarForm(forms.ModelForm):
    drivers = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
        required=False
    )

    class Meta:
        model = Car
        fields = "__all__"


class CarSearchForm(forms.Form):
    model = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by model..."})
    )

taxi/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.shortcuts import render
from django.views import generic


from taxi.models import Driver, Car, Manufacturer
from taxi.forms import DriverCreationForm, LicenseForm, CarForm, CarSearchForm


@login_required
def index(request):
    """View function for the home page of the site."""

    num_drivers = Driver.objects.count()
    num_cars = Car.objects.count()
    num_manufacturers = Manufacturer.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_drivers": num_drivers,
        "num_cars": num_cars,
        "num_manufacturers": num_manufacturers,
        "num_visits": num_visits + 1,
    }

    return render(request, "taxi/index.html", context=context)


class ManufacturerListView(LoginRequiredMixin, generic.ListView):
    model = Manufacturer
    paginate_by = 5


class ManufacturerCreateView(LoginRequiredMixin, generic.CreateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Manufacturer
    fields = "__all__"
    success_url = reverse_lazy("taxi:manufacturer-list")


class ManufacturerDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Manufacturer
    success_url = reverse_lazy("taxi:manufacturer-list")
    template_name = "taxi/manufacturer_confirm_delete.html"


class CarListView(LoginRequiredMixin, generic.ListView):
    model = Car
    paginate_by = 5
    queryset = Car.objects.all().select_related("manufacturer")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(CarListView, self).get_context_data(**kwargs)
        model = self.request.GET.get("model", "")
        context["search_form"] = CarSearchForm(
            initial={"model": model}
        )
        return context

    def get_queryset(self):
        form = CarSearchForm(self.request.GET)
        if form.is_valid():
            return self.queryset.filter(
                model__istartswith=form.cleaned_data["model"]
            )
        return self.queryset


class CarDetailView(LoginRequiredMixin, generic.DetailView):
    model = Car


class CarCreateView(LoginRequiredMixin, generic.CreateView):
    model = Car
    form_class = CarForm
    success_url = reverse_lazy("taxi:car-list")


class CarUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Car
    form_class = CarForm
    success_url = reverse_lazy("taxi:car-list")


class CarDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Car
    success_url = reverse_lazy("taxi:car-list")
    template_name = "taxi/car_confirm_delete.html"


class DriverListView(LoginRequiredMixin, generic.ListView):
    model = Driver
    paginate_by = 5


class DriverDetailView(LoginRequiredMixin, generic.DetailView):
    model = Driver
    queryset = Driver.objects.all().prefetch_related("cars__manufacturer")


class DriverCreateView(LoginRequiredMixin, generic.CreateView):
    model = Driver
    form_class = DriverCreationForm


class DriverUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Driver
    form_class = DriverCreationForm


class DriverDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Driver
    success_url = reverse_lazy("taxi:driver-list")
    template_name = "taxi/driver_confirm_delete.html"


class LicenseUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Driver
    form_class = LicenseForm
    template_name = "taxi/license_form.html"

templates/taxi/car_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Car</h1>

  <p>Are you sure you want to delete the car: {{ car.model }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  </form>

{% endblock %}

templates/taxi/car_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>Car model: {{ car.model }}</h1>
  <p><strong>Manufacturer:</strong> {{ car.manufacturer.name }}</p>
  <p><strong>Country:</strong> {{ car.manufacturer.country }}</p>
  <div class="ml-4">
    <h2>Drivers</h2>
    {% for driver in car.drivers.all %}
        <hr>
        <p><strong>Username:</strong>
          <a href="{% url 'taxi:driver-detail' pk=driver.id %}" class="btn btn-outline-primary">
            {{ driver.username }}
          </a>
        </p>
        <p><strong>Full name:</strong> {{ driver.first_name }} {{ driver.last_name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{driver.id}}</p>
    {% empty %}
      <p>No drivers!</p>
    {% endfor %}
  </div>
  <form action="{% url "taxi:car-update" pk=car.id %}">
    {% csrf_token %}
    <input type="submit" value="Update Car" class="btn btn-primary floated"/>
  </form>
  <form action="{% url "taxi:car-delete" pk=car.id %}">
    {% csrf_token %}
    <input type="submit" value="Delete Car" class="btn btn-primary floated"/>
  </form>
{% endblock %}

templates/taxi/car_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Car</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary"/>
  </form>
{% endblock %}

templates/taxi/car_list.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Car list
    <a href="{% url "taxi:car-create" %}" class="btn btn-primary" style="float: right">
      Create Car
    </a>
  </h1>
  <form action="" method="get" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" class="btn btn-secondary" value="&#128269">
  </form>
  <br>
  {% if car_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Model</th>
        <th>Manufacturer</th>
        <th>Country</th>
        <th>Drivers</th>
      </tr>
      {% for car in car_list %}
        <tr>
          <td>{{ car.id }}</td>
          <td>
            <a href="{% url "taxi:car-detail" pk=car.id %}" class="btn btn-outline-primary">
              {{ car.model }}
            </a>
          </td>
          <td>{{ car.manufacturer.name }}</td>
          <td>{{ car.manufacturer.country }}</td>
          <td>{{ car.drivers.count }}</td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
    <p>There are no cars in taxi</p>
  {% endif %}
{% endblock %}

templates/taxi/driver_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Driver</h1>

  <p>Are you sure you want to delete the driver: {{ driver.username }}?</p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  </form>

{% endblock %}

templates/taxi/driver_detail.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Username: {{ driver.username }}
  </h1>

  <p><strong>First name:</strong> {{ driver.first_name }}</p>
  <p><strong>Last name:</strong> {{ driver.last_name }}</p>
  <p>
    <strong>License number:</strong> {{ driver.license_number }}
    <a href="{% url "taxi:license-update" pk=driver.id %}" class="btn btn-info">
      Update
    </a>
  </p>
  <p><strong>Is staff:</strong> {{ driver.is_staff }}</p>

  <div class="ml-4">
    <h3>Cars</h3>

    {% for car in driver.cars.all %}
        <hr>
        <p><strong>Model:</strong>
          <a href="{% url 'taxi:car-detail' pk=car.id %}" class="btn btn-outline-primary">
            {{ car.model }}
          </a>
        </p>
        <p><strong>Manufacturer:</strong> {{ car.manufacturer.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{car.id}}</p>

    {% empty %}
      <p>No cars!</p>
    {% endfor %}
  </div>
  <form action="{% url "taxi:driver-update" pk=driver.id %}">
    {% csrf_token %}
    <input type="submit" value="Update Driver" class="btn btn-primary floated"/>
  </form>
  <form action="{% url "taxi:driver-delete" pk=driver.id %}">
    {% csrf_token %}
    <input type="submit" value="Delete Driver" class="btn btn-primary floated"/>
  </form>
{% endblock %}

templates/taxi/driver_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Driver</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary"/>
  </form>
{% endblock %}

templates/taxi/driver_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Driver List
    <a href="{% url "taxi:driver-create" %}" class="btn btn-primary" style="float: right">
      Create Driver
    </a>
  </h1>
  {% if driver_list %}
  <table class="table">
    <tr>
      <th>ID</th>
      <th>Username</th>
      <th>First name</th>
      <th>Last name</th>
      <th>License number</th>
      <th>Cars</th>
      <th>Is staff</th>
    </tr>
  {% for driver in driver_list %}
    <tr>
      <td>{{ driver.id }}</td>
      <td>
        <a href="{{ driver.get_absolute_url }}" class="btn btn-success">
          {{ driver.username }} {% if user == driver %} (Me){% endif %}
        </a>
      </td>
      <td>{{ driver.first_name }}</td>
      <td>{{ driver.last_name }}</td>
      <td>{{ driver.license_number }}</td>
      <td>{{ driver.cars.count }}</td>
      <td>{% if driver.is_staff %}YES{% else %}NO{% endif %}</td>
    </tr>
  {% endfor %}

  </table>
  {% else %}
    <p>There are no drivers in the service.</p>
  {% endif %}
{% endblock %}

templates/taxi/index.html
{% extends "base.html" %}

{% block content %}
    <h1>Taxi Service Home</h1>
    <p>Welcome to Best Taxi Ever!</p>
    <h2>Dynamic content</h2>
    <p>The Taxi service has the following record counts:</p>
    <ul>
        <li><strong>Cars:</strong> {{ num_cars }}</li>
        <li><strong>Drivers:</strong> {{ num_drivers }}</li>
        <li><strong>Manufacturers:</strong> {{ num_manufacturers }}</li>
    </ul>

    <p>You have visited this page
        {{ num_visits }} time{{ num_visits|pluralize }}.
    </p>

{% endblock %}

templates/taxi/license_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Update License Number</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary"/>
  </form>
{% endblock %}

templates/taxi/manufacturer_confirm_delete.html
{% extends "base.html" %}

{% block content %}

  <h1>Delete Manufacturer</h1>

  <p>Are you sure you want to delete the manufacturer: {{ manufacturer.name }}?</p>
  <p><i>All cars with this manufacturer will be also deleted!</i></p>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, delete" class="btn btn-danger"/>
  </form>

{% endblock %}

templates/taxi/manufacturer_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Manufacturer</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary"/>
  </form>
{% endblock %}

templates/taxi/manufacturer_list.html
{% extends "base.html" %}

{% block content %}
  <h1>
    Manufacturer List
    <a href="{% url "taxi:manufacturer-create" %}" class="btn btn-primary" style="float: right">
      Create Manufacturer
    </a>
  </h1>
  {% if manufacturer_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Country</th>
        <th>Cars</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for manufacturer in manufacturer_list %}
        <tr>
          <td>{{ manufacturer.id }}</td>
          <td>{{ manufacturer.name }}</td>
          <td>{{ manufacturer.country }}</td>
          <td>{{ manufacturer.car_set.count }}</td>
          <td>
            <a href="{% url "taxi:manufacturer-update" pk=manufacturer.id %}" class="btn btn-secondary btn-sm">
              Update
            </a>
          </td>
          <td>
            <a href="{% url "taxi:manufacturer-delete" pk=manufacturer.id %}" class="btn btn-secondary btn-sm">
              Delete
            </a>
          </td>
        </tr>
      {% endfor %}
    </table>
  {% else %}
      <p>There are no manufacturers in the service.</p>
  {% endif %}
{% endblock %}